### ISSUE TITLE
加入文件后提示 fbxmanager is not defined

### ISSUE THREAD

**Issue by jonyzhang2023** [Shi-Iho/FBX-Python-SDK-for-Python3.x#1]
hi:
     感谢分享！
     我在使用中将三个文件加入 site-package 并创建了空的fbx文件夹。使用时报错 “fbxmanager is not defined”，看起来是fbx.pyd没有被找见。请问这个文件有别的问题嘛？

**Comment by jonyzhang2023** [comment]
I have done this by rebuilding sdk myself.

**Comment by Shiiho11** [comment]
hi:
我很抱歉回复迟了，我已经不研究这个内容，无法解答你的问题。
很高兴看到你自己找到了解决方法。

I apologize for the late reply. I have stopped researching this content and am unable to answer your question.
I'm glad to see that you have found a solution yourself.
👍
